spring:
  application:
    name: limits-service
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/postgres}
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USER:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true


limits:
  default-amount: ${DEFAULT_LIMIT:10000}
  reset:
    cron: ${RESET_CRON:0 0 0 * * ?}